package com.example.viewmodel

import androidx.lifecycle.ViewModel
import androidx.lifecycle.ViewModelProvider
import androidx.lifecycle.viewModelScope
import com.example.data.Tenant
import com.example.data.TenantRepository
import kotlinx.coroutines.delay
import kotlinx.coroutines.flow.SharingStarted
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.stateIn
import kotlinx.coroutines.launch
import java.util.Base64
import kotlin.random.Random

class TenantViewModel(private val repository: TenantRepository) : ViewModel() {

    val tenants: StateFlow<List<Tenant>> = repository.allTenants
        .stateIn(
            scope = viewModelScope,
            started = SharingStarted.WhileSubscribed(5000),
            initialValue = emptyList()
        )

    fun addTenant(name: String, packageName: String) {
        viewModelScope.launch {
            repository.insert(Tenant(name = name, packageName = packageName))
        }
    }

    fun deleteTenant(id: Int) {
        viewModelScope.launch {
            repository.deleteById(id)
        }
    }

    // Simulate GitHub Actions Build
    fun triggerBuild(tenant: Tenant) {
        viewModelScope.launch {
            // Update status to building
            repository.update(tenant.copy(lastBuildStatus = "Building..."))
            
            // Simulate network delay for GitHub Actions
            delay(2000)

            var newKeystore: String? = tenant.keystoreBase64
            var status = "Success"

            if (tenant.keystoreBase64 == null) {
                // Phase 1: New build, keystore generated by GitHub actions mock
                val randomKey = ByteArray(32)
                Random.nextBytes(randomKey)
                newKeystore = Base64.getEncoder().encodeToString(randomKey)
                status = "Success (Generated Keystore)"
            } else {
                // Phase 2: Update build using existing Keystore
                status = "Success (Used Existing Keystore)"
            }

            repository.update(
                tenant.copy(
                    keystoreBase64 = newKeystore,
                    lastBuildStatus = status,
                    lastBuildTime = System.currentTimeMillis()
                )
            )
        }
    }
}

class TenantViewModelFactory(private val repository: TenantRepository) : ViewModelProvider.Factory {
    override fun <T : ViewModel> create(modelClass: Class<T>): T {
        if (modelClass.isAssignableFrom(TenantViewModel::class.java)) {
            @Suppress("UNCHECKED_CAST")
            return TenantViewModel(repository) as T
        }
        throw IllegalArgumentException("Unknown ViewModel class")
    }
}
